### ISSUE TITLE
Challenge Four, asking for wrong coordinate

### ISSUE THREAD

**Issue by K0r1g4n** [reoky/android-crackme-challenge#8]
The challenge source code is checking for coordinate: 45.xxx,-93.xxx,
but the coordinate in the description ask for: 44.xxx,-93.xxx
Source file to fix: ChallengeFourFragment.java line 79
or: res/values/string.xml line 10

**Comment by reoky** [comment]
Thanks, and good notice.

**Comment by reoky** [comment]
https://github.com/reoky/android-crackme-challenge/pull/9

**Comment by K0r1g4n** [comment]
Good job and thanks for your work :)

**Comment by K0r1g4n** [comment]
No problem bro :)
I only regret there weren't more challenge :)
They were great!
Thanks to you!


Le 18/01/2018 02:15, Lucas a écrit :

**Comment by TGThorax** [comment]
Please update the download links as well or at least temporarily remove the link. I searched way too long, since it's now corrected in code... ;)
